config/routes.rb
Rails.application.routes.draw do
  resources :books
  root to: 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :book_genres
  has_many :genres, through: :book_genres

  before_save :set_keywords

  scope :finished, ->  { where.not(finished_on: nil) }

  scope :recent, -> { where('finished_on > ?', 2.days.ago)}

  scope :search, -> (keyword) { where('keywords LIKE ?', "%#{keyword.downcase}%") if keyword.present? }

  scope :filter_by_genre, -> (genre) { joins(:genres).where(genres: { name: genre }) if genre.present? }

  def finished?
    finished_on.present?
  end

  protected

  def set_keywords
    self.keywords = [title, author, description].map(&:downcase).join(' ')
  end
end

app/models/book_genre.rb
class BookGenre < ActiveRecord::Base
  belongs_to :book
  belongs_to :genre
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :book_genres
  has_many :books, through: :book_genres
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.includes(:genres).search(params[:keyword]).filter_by_genre(params[:genre])
    @genres = Genre.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :description, :amazon_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def image_from_amazon(amazon_id)
    image_tag "http://images.amazon.com/images/P/#{amazon_id}.01.ZTZZZZZZ.jpg"
  end
end

app/views/books/_book.html.erb
<tr class='<%= "finished" if book.finished? %>'>
  <td><%= image_from_amazon(book.amazon_id) %></td>
  <td><%= book.title %></td>
  <td><%= book.author %></td>
  <td><%= book.description %></td>
  <td><%= book.amazon_id %></td>
  <td>
    <% book.genres.each do |genre| %>
      <%= link_to genre.name, '#', class: 'label label-primary' %>
    <% end %>
  </td>
  <td><%= link_to 'Show', book %></td>
  <td><%= link_to 'Edit', edit_book_path(book) %></td>
  <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :amazon_id %><br>
    <%= f.text_field :amazon_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>
<form>
  <legend>Search</legend>
  <input type='text' class='form-control' value='<%= params[:keyword] %>' name='keyword' placeholder='Find a book...'>
</form>
<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>Author</th>
      <th>Description</th>
      <th>Amazon</th>
      <th>Genres</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @books %>
  </tbody>
</table>
<div>
  <h2>Genres</h2>
  <ul>
    <% @genres.each do |genre| %>
      <li>
        <%= link_to genre.name, books_path(genre: genre.name) %>
      </li>
    <% end %>
  </ul>
</div>
<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Amazon:</strong>
  <%= @book.amazon_id %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReadingList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>